# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chapter_info.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chapter_info.proto',
  package='TableProto',
  serialized_pb='\n\x12\x63hapter_info.proto\x12\nTableProto\"r\n\x0c\x63hapter_info\x12\r\n\x02ID\x18\x01 \x02(\x05:\x01\x30\x12\x12\n\x08material\x18\x02 \x01(\t:\x00\x12\x0e\n\x04path\x18\x03 \x01(\t:\x00\x12\x0e\n\x04name\x18\x04 \x01(\t:\x00\x12\x0f\n\x05scene\x18\x05 \x01(\t:\x00\x12\x0e\n\x06sprite\x18\x06 \x03(\x05\"=\n\x12\x63hapter_info_ARRAY\x12\'\n\x05items\x18\x01 \x03(\x0b\x32\x18.TableProto.chapter_info')




_CHAPTER_INFO = _descriptor.Descriptor(
  name='chapter_info',
  full_name='TableProto.chapter_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='TableProto.chapter_info.ID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='material', full_name='TableProto.chapter_info.material', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='TableProto.chapter_info.path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='TableProto.chapter_info.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scene', full_name='TableProto.chapter_info.scene', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sprite', full_name='TableProto.chapter_info.sprite', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=148,
)


_CHAPTER_INFO_ARRAY = _descriptor.Descriptor(
  name='chapter_info_ARRAY',
  full_name='TableProto.chapter_info_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='TableProto.chapter_info_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=150,
  serialized_end=211,
)

_CHAPTER_INFO_ARRAY.fields_by_name['items'].message_type = _CHAPTER_INFO
DESCRIPTOR.message_types_by_name['chapter_info'] = _CHAPTER_INFO
DESCRIPTOR.message_types_by_name['chapter_info_ARRAY'] = _CHAPTER_INFO_ARRAY

class chapter_info(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHAPTER_INFO

  # @@protoc_insertion_point(class_scope:TableProto.chapter_info)

class chapter_info_ARRAY(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHAPTER_INFO_ARRAY

  # @@protoc_insertion_point(class_scope:TableProto.chapter_info_ARRAY)


# @@protoc_insertion_point(module_scope)
