# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hero_info.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hero_info.proto',
  package='TableProto',
  serialized_pb='\n\x0fhero_info.proto\x12\nTableProto\"\xa2\x02\n\tHERO_INFO\x12\r\n\x02ID\x18\x01 \x02(\x05:\x01\x30\x12\x12\n\x08hero_res\x18\x02 \x01(\t:\x00\x12\x0e\n\x04name\x18\x03 \x01(\t:\x00\x12\x0e\n\x03sex\x18\x04 \x01(\x05:\x01\x30\x12\x0f\n\x04type\x18\x05 \x01(\x05:\x01\x30\x12\x0f\n\x04\x63\x61mp\x18\x06 \x01(\x05:\x01\x30\x12\x12\n\x07quality\x18\x07 \x01(\x05:\x01\x30\x12\x14\n\tlevel_max\x18\x08 \x01(\x05:\x01\x30\x12\x13\n\thero_icon\x18\t \x01(\t:\x00\x12\x16\n\x0c\x61ttack_skill\x18\n \x01(\t:\x00\x12\x17\n\rpassive_skill\x18\x0b \x01(\t:\x00\x12\x0f\n\x05skill\x18\x0c \x01(\t:\x00\x12\x18\n\x0eultimate_skill\x18\r \x01(\t:\x00\x12\x15\n\x0b\x64\x65scription\x18\x0e \x01(\t:\x00\"7\n\x0fHERO_INFO_ARRAY\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.TableProto.HERO_INFO')




_HERO_INFO = _descriptor.Descriptor(
  name='HERO_INFO',
  full_name='TableProto.HERO_INFO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='TableProto.HERO_INFO.ID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hero_res', full_name='TableProto.HERO_INFO.hero_res', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='TableProto.HERO_INFO.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sex', full_name='TableProto.HERO_INFO.sex', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='TableProto.HERO_INFO.type', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='camp', full_name='TableProto.HERO_INFO.camp', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quality', full_name='TableProto.HERO_INFO.quality', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level_max', full_name='TableProto.HERO_INFO.level_max', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hero_icon', full_name='TableProto.HERO_INFO.hero_icon', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack_skill', full_name='TableProto.HERO_INFO.attack_skill', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='passive_skill', full_name='TableProto.HERO_INFO.passive_skill', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skill', full_name='TableProto.HERO_INFO.skill', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ultimate_skill', full_name='TableProto.HERO_INFO.ultimate_skill', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='TableProto.HERO_INFO.description', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=322,
)


_HERO_INFO_ARRAY = _descriptor.Descriptor(
  name='HERO_INFO_ARRAY',
  full_name='TableProto.HERO_INFO_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='TableProto.HERO_INFO_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=324,
  serialized_end=379,
)

_HERO_INFO_ARRAY.fields_by_name['items'].message_type = _HERO_INFO
DESCRIPTOR.message_types_by_name['HERO_INFO'] = _HERO_INFO
DESCRIPTOR.message_types_by_name['HERO_INFO_ARRAY'] = _HERO_INFO_ARRAY

class HERO_INFO(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HERO_INFO

  # @@protoc_insertion_point(class_scope:TableProto.HERO_INFO)

class HERO_INFO_ARRAY(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HERO_INFO_ARRAY

  # @@protoc_insertion_point(class_scope:TableProto.HERO_INFO_ARRAY)


# @@protoc_insertion_point(module_scope)
