//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sprite_info.proto
namespace TableProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sprite_info")]
  public partial class sprite_info : global::ProtoBuf.IExtensible
  {
    public sprite_info() {}
    
    private int _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private string _path = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _is_show = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"is_show", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int is_show
    {
      get { return _is_show; }
      set { _is_show = value; }
    }
    private int _event_type = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"event_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int event_type
    {
      get { return _event_type; }
      set { _event_type = value; }
    }
    private float _box_size_x = (float)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"box_size_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float box_size_x
    {
      get { return _box_size_x; }
      set { _box_size_x = value; }
    }
    private float _box_size_y = (float)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"box_size_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float box_size_y
    {
      get { return _box_size_y; }
      set { _box_size_y = value; }
    }
    private float _box_size_z = (float)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"box_size_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float box_size_z
    {
      get { return _box_size_z; }
      set { _box_size_z = value; }
    }
    private float _box_pos_x = (float)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"box_pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float box_pos_x
    {
      get { return _box_pos_x; }
      set { _box_pos_x = value; }
    }
    private float _box_pos_y = (float)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"box_pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float box_pos_y
    {
      get { return _box_pos_y; }
      set { _box_pos_y = value; }
    }
    private float _box_pos_z = (float)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"box_pos_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float box_pos_z
    {
      get { return _box_pos_z; }
      set { _box_pos_z = value; }
    }
    private float _orig_posi_x = (float)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"orig_posi_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float orig_posi_x
    {
      get { return _orig_posi_x; }
      set { _orig_posi_x = value; }
    }
    private float _orig_posi_y = (float)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"orig_posi_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float orig_posi_y
    {
      get { return _orig_posi_y; }
      set { _orig_posi_y = value; }
    }
    private float _orig_posi_z = (float)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"orig_posi_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float orig_posi_z
    {
      get { return _orig_posi_z; }
      set { _orig_posi_z = value; }
    }
    private float _target_x = (float)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"target_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float target_x
    {
      get { return _target_x; }
      set { _target_x = value; }
    }
    private float _target_y = (float)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"target_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float target_y
    {
      get { return _target_y; }
      set { _target_y = value; }
    }
    private float _target_z = (float)0;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"target_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float target_z
    {
      get { return _target_z; }
      set { _target_z = value; }
    }
    private int _sorting_layer = (int)0;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"sorting_layer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int sorting_layer
    {
      get { return _sorting_layer; }
      set { _sorting_layer = value; }
    }
    private float _pos_delay = (float)0;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"pos_delay", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float pos_delay
    {
      get { return _pos_delay; }
      set { _pos_delay = value; }
    }
    private float _pos_dura = (float)0;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"pos_dura", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float pos_dura
    {
      get { return _pos_dura; }
      set { _pos_dura = value; }
    }
    private int _pos_type = (int)0;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"pos_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int pos_type
    {
      get { return _pos_type; }
      set { _pos_type = value; }
    }
    private int _re_pos_type = (int)0;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"re_pos_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int re_pos_type
    {
      get { return _re_pos_type; }
      set { _re_pos_type = value; }
    }
    private float _orig_scale_x = (float)0;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"orig_scale_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float orig_scale_x
    {
      get { return _orig_scale_x; }
      set { _orig_scale_x = value; }
    }
    private float _orig_scale_y = (float)0;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"orig_scale_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float orig_scale_y
    {
      get { return _orig_scale_y; }
      set { _orig_scale_y = value; }
    }
    private float _orig_scale_z = (float)0;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"orig_scale_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float orig_scale_z
    {
      get { return _orig_scale_z; }
      set { _orig_scale_z = value; }
    }
    private float _target_scale_x = (float)0;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"target_scale_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float target_scale_x
    {
      get { return _target_scale_x; }
      set { _target_scale_x = value; }
    }
    private float _target_scale_y = (float)0;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"target_scale_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float target_scale_y
    {
      get { return _target_scale_y; }
      set { _target_scale_y = value; }
    }
    private float _target_scale_z = (float)0;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"target_scale_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float target_scale_z
    {
      get { return _target_scale_z; }
      set { _target_scale_z = value; }
    }
    private float _scale_delay = (float)0;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"scale_delay", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float scale_delay
    {
      get { return _scale_delay; }
      set { _scale_delay = value; }
    }
    private float _scale_drua = (float)0;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"scale_drua", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float scale_drua
    {
      get { return _scale_drua; }
      set { _scale_drua = value; }
    }
    private int _scale_type = (int)0;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"scale_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int scale_type
    {
      get { return _scale_type; }
      set { _scale_type = value; }
    }
    private int _re_scale_type = (int)0;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"re_scale_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int re_scale_type
    {
      get { return _re_scale_type; }
      set { _re_scale_type = value; }
    }
    private float _orig_rat_x = (float)0;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"orig_rat_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float orig_rat_x
    {
      get { return _orig_rat_x; }
      set { _orig_rat_x = value; }
    }
    private float _orig_rat_y = (float)0;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"orig_rat_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float orig_rat_y
    {
      get { return _orig_rat_y; }
      set { _orig_rat_y = value; }
    }
    private float _orig_rat_z = (float)0;
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"orig_rat_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float orig_rat_z
    {
      get { return _orig_rat_z; }
      set { _orig_rat_z = value; }
    }
    private float _target_rat_x = (float)0;
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"target_rat_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float target_rat_x
    {
      get { return _target_rat_x; }
      set { _target_rat_x = value; }
    }
    private float _target_rat_y = (float)0;
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"target_rat_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float target_rat_y
    {
      get { return _target_rat_y; }
      set { _target_rat_y = value; }
    }
    private float _target_rat_z = (float)0;
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"target_rat_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float target_rat_z
    {
      get { return _target_rat_z; }
      set { _target_rat_z = value; }
    }
    private float _rat_delay = (float)0;
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"rat_delay", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float rat_delay
    {
      get { return _rat_delay; }
      set { _rat_delay = value; }
    }
    private float _rat_drua = (float)0;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"rat_drua", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0)]
    public float rat_drua
    {
      get { return _rat_drua; }
      set { _rat_drua = value; }
    }
    private int _rat_type = (int)0;
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"rat_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int rat_type
    {
      get { return _rat_type; }
      set { _rat_type = value; }
    }
    private int _re_rat_type = (int)0;
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"re_rat_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int re_rat_type
    {
      get { return _re_rat_type; }
      set { _re_rat_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sprite_info_ARRAY")]
  public partial class sprite_info_ARRAY : global::ProtoBuf.IExtensible
  {
    public sprite_info_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<TableProto.sprite_info> _items = new global::System.Collections.Generic.List<TableProto.sprite_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TableProto.sprite_info> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}